config/routes.rb
Rails.application.routes.draw do
  get 'games/main'
  devise_for :users
  root to: 'stories#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :units, only: :index
  resources :user_units, only: [:create, :new]
  get 'inventory', to: "user_resources#index"
  get 'inventory/:id', to: "user_resources#update"
  get 'base', to: "games#index"
  get 'base/checkupdate', to: "games#getupdate"
  patch 'base', to: "games#update"
  post 'games/extract', to: "extracts#pick_up"
  post 'inventory/exchange', to: "user_resources#exchange"
  post 'structures/buy', to: "user_structures#build"
  post '/upload', to: "games#upload"
  post 'soldiers/buy', to: "user_units#create"
  get 'story', to: "stories#show"
  get 'base/raid', to: "games#raid"
  get '/raid/:id', to: "games#startraid"
  get '/friends/search/:input', to: "friends#searchfriend"
  post '/friends/add', to: "friends#addfriend"
  post '/friends/acceptfriend', to: "friends#acceptfriend"
  get '/friends', to: "friends#index"
  get '/friends/randomfriends', to: "friends#randomfriends"
  get '/friends/friendrequests', to: "friends#myfriendrequest"
  get '/friends/show', to: "friends#show"
  post '/games/mylocation', to: "extracts#updateresource"
  get 'desktop', to: "games#desktop"
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  require 'open-uri'
  skip_before_action :verify_authenticity_token
  def main
  end

  def index
    if !current_user.nil?
      render json: {msg: current_user.base,imgupdate: current_user.imgupdate}
    else
      render json: {msg: 'please log in!'}
    end
  end

  def desktop
    # raise
  end

  def getupdate
    if !current_user.nil?
      user_structures = current_user.user_structures
      unplaced = user_structures.where.not("amount = placed") # check if there is building the has been bought and not placed
      returnlist = []
      unplaced.each do |user_structure|
        amount = user_structure.amount - user_structure.placed
        strname = user_structure.structure.unit_name
        returnlist << {strname => amount}
      end
      (returnlist.count.zero?) ? (render json: {result: false}) : (render json: {msg: returnlist, result: true})
    else
      render json: {msg: 'please log in!', result: false}
    end
  end

  def update
    if !current_user.nil?
      ## here should be checking if has structure
      if !params['base'].nil? && (params['base'].match? (/layer3.putTilesAt\(buildings_type\['.+'\],\d+,\d+\);/))
      structure = Structure.find_by(unit_name: params['name'])
      user_structure = current_user.user_structures.find_by(structure: structure)
      if user_structure.amount > user_structure.placed
        user_structure.placed += 1
        user_structure.save!
        current_user.base << params['base']
        current_user.save!
        render json: {error: '200'}
      else
        render json: {msg: 'you dont have this structure',error: '501'}
      end
      else
        render json: {msg: 'Invalid data'}
      end
    else
      render json: {msg: 'please log in!'}
    end
  end

  def upload
    if !current_user.nil?
      basephoto = params['_json']
      image = Cloudinary::Uploader.upload(basephoto)
      file = open(image["url"])
      current_user.photo.attach(io: file, filename: 'base.jpg', content_type: 'image/png')
      current_user.update(imgupdate: false)
    end
  end

  def raid
    if !current_user.nil?
      @enemis = []
      @enemis = User.all
      # @enemis = User.where.not(id: current_user.id).shuffle[0..20]
    end
  end

  def startraid
    id = params['id']
      if !current_user.nil?
        if current_user.raidcount < 2
          if !User.find(id).nil?
            checkwon(User.find(id))
            current_user.raidcount += 1
            current_user.save!
          else
            flash[:notice] = 'invalid user'
            redirect_to games_main_path
          end
        else
          flash[:notice] = 'You have exceeded 2 raids for today :('
          redirect_to games_main_path
        end
      else
      redirect_to new_user_session_path
      end
  end

    private

    def checkwon(enemyuser)
      myuser = [0,0,0,0] # 0 - power , 1 - defense, 2 - range, 3 - hp
      enemy  = [0,0,0,0]
      won = 'You won congratz !'
      current_user.user_units.each do |myunit|
        myuser[0] += myunit.unit.attack
        myuser[1] += myunit.unit.defense
        myuser[2] += myunit.unit.range
        myuser[3] += myunit.unit.hp
      end
      enemyuser.user_units.each do |myunit|
        enemy[0] += myunit.unit.attack
        enemy[1] += myunit.unit.defense
        enemy[2] += myunit.unit.range
        enemy[3] += myunit.unit.hp
      end
      if myuser.inject(:+) > enemy.inject(:+)
        amount = current_user.user_resources.first.amount
        amountsecond = current_user.user_resources.second.amount
        current_user.user_resources.first.update(amount: (amount += 20))
        current_user.user_resources.second.update(amount: (amount += 20))
      else
        amount = current_user.user_resources.first.amount
        amountsecond = current_user.user_resources.second.amount
        enemyuser.user_resources.first.update(amount: (amount += 20))
        enemyuser.user_resources.second.update(amount: (amount += 20))
        won = 'You lost try next time !'
      end
      flash[:notice] = won
      redirect_to games_main_path
    end
end

app/views/games/desktop.html.erb
<div class="flex">
  <div class="site">
    <div class="sketch">
      <div class="bee-sketch red"></div>
      <div class="bee-sketch blue"></div>
    </div>

  <h1 class="desktop">404:
    <small>We dont support Desktop<br>Please move to mobile ER 😊</small></h1>
  </div>
</div>

app/views/games/main.html.erb
<div class="dropdown menu">
  <img src='<%= asset_path('menu.svg') %>'  class="avatar dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"/>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" id="switch" href="#">
      <img class="avatar" src='<%= asset_path('warp.png') %>' alt="">
      Time Travel
    </a>
    <a class="dropdown-item" id="shop" href="<%= new_user_unit_path %>">
      <img class="avatar" src="<%= asset_path('shop.svg') %>" alt="">
      Shop
    </a>
    <a class="dropdown-item" onclick="alert('On development see beta\n using Tasks and user power and defense algorithm')" id="raid" href="<%= base_raid_path %>">
      <img class="avatar" src="<%= asset_path('sword.svg') %>" alt="">
      Raid
    </a>
    <a class="dropdown-item" onclick="alert('On development React based friends system')" id="friend" href="<%= friends_show_path %>">
      <img class="avatar" src="<%= asset_path('sword.svg') %>" alt="">
      Friends
    </a>
  </div>
</div>
<div class="loading">
  <h1>LOADING...</h1>
  <h1>First load</h1>
  <h1>Takes time.</h1>
  <div class="lds-facebook"><div></div><div></div><div></div></div>
</div>
    <div class="con" style="padding: 0">
      <div id="map"
        data-markers="<%= @cache_resources.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
<div id="phaser-app"></div>

app/views/games/raid.html.erb
<div class="container" style="padding:0">
  <div class="banner" style="margin-top: 40px;margin-bottom: 16px;">
    <h1>Select your Opponent</h1>
  </div>
  <div class="cards">
    <% @enemis[0..1].each do |enemy| %>
    <% resource = current_user.user_resources.sample %>
      <div class="card-trip">
        <% if enemy.photo.attached? %>
          <%= cl_image_tag enemy.photo.key, crop: :fit %>
        <% else %>
          <img src="https://res.cloudinary.com/dgq92f6st/image/upload/c_fit/CCcqtKKBK1sX4JwFdYbUt9DN.png" alt="">
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2>IGN: <%= enemy.nickname %></h2>
            <p><br>Units : <%= enemy.user_units.count %>
              <br>Gems : <%= enemy.gems %>
              <br><%= resource.resource.name %> : <%= resource.amount %>
          </p>
          <a href="../raid/<%= enemy.id %>" class="btn btn-danger"style="text-align: center;margin-right: 40%;margin-left: 40%;margin-top:8px;opacity: 0.7">RAID</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="raid-action fixed-bottom">
    <h3 class=".text-info btn-secondary btn-lg pm">Today Raids: <%= current_user.raidcount %></h3>
    <a class=".text-info btn btn-secondary btn-lg text-center pm" href="<%= games_main_path %>">Main screen</a>
  </div>
</div>