config/routes.rb
Rails.application.routes.draw do
  get 'games/main'
  devise_for :users
  root to: 'stories#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :units, only: :index
  resources :user_units, only: [:create, :new]
  get 'inventory', to: "user_resources#index"
  get 'inventory/:id', to: "user_resources#update"
  get 'base', to: "games#index"
  get 'base/checkupdate', to: "games#getupdate"
  patch 'base', to: "games#update"
  post 'games/extract', to: "extracts#pick_up"
  post 'inventory/exchange', to: "user_resources#exchange"
  post 'structures/buy', to: "user_structures#build"
  post '/upload', to: "games#upload"
  post 'soldiers/buy', to: "user_units#create"
  get 'story', to: "stories#show"
  get 'base/raid', to: "games#raid"
  get '/raid/:id', to: "games#startraid"
  get '/friends/search/:input', to: "friends#searchfriend"
  post '/friends/add', to: "friends#addfriend"
  post '/friends/acceptfriend', to: "friends#acceptfriend"
  get '/friends', to: "friends#index"
  get '/friends/randomfriends', to: "friends#randomfriends"
  get '/friends/friendrequests', to: "friends#myfriendrequest"
  get '/friends/show', to: "friends#show"
  post '/games/mylocation', to: "extracts#updateresource"
  get 'desktop', to: "games#desktop"
end

app/models/user_unit.rb
class UserUnit < ApplicationRecord
  belongs_to :unit
  belongs_to :user
end

app/controllers/user_units_controller.rb
class UserUnitsController < ApplicationController
  skip_before_action :verify_authenticity_token
  TENROLL = 90
  ONEROLL = 10

  def create
    if current_user.nil?
      # TO DO: render something
      return
    end
    amount = params[:unit_amount].to_i
    @error = nil
    @units = []
    case amount
    when 10
      if checkgems(TENROLL)
        response = []
        10.times do |i|
          result = generate
          unit = Unit.where(rarity: result.downcase).sample
          UserUnit.create(unit_id: unit.id, user_id: current_user.id)
          @units << {
            name: unit.name,
            rarity: unit.rarity,
            attack: unit.attack,
            defense: unit.defense
          }
        end
        current_user.gems -= TENROLL
        current_user.save!
      else
        @error = "Missing: #{(current_user.gems - TENROLL).abs} gems."
      end
    when 1
      if checkgems(ONEROLL)
        result = generate
        unit = Unit.where(rarity: result.downcase).sample
        UserUnit.create(unit: unit, user: current_user)
        current_user.gems -= ONEROLL
        current_user.save!
        @units << {
          name: unit.name,
          rarity: unit.rarity,
          attack: unit.attack,
          defense: unit.defense
        }
      else
        @error = "Missing: #{(current_user.gems - ONEROLL).abs} gems."
      end
    end
    @resources = current_user.resources_amounts
  end

  def new
    @resources = current_user.resources_amounts
  end

  private
  def user_units_params(params)
    params.require(:user_units).permit(:amount)
  end

  def generate
    luck = rand(1..100)
    case luck
    when 1..5
      result = 'SS'
    when 6..16
      result = 'S'
    when 17..37
      result = 'A'
    when 38..100
      result = 'B'
    end
  end

  def checkgems(option)
    (current_user.gems - option) >= 0
  end

end

app/views/user_units/create.js.erb
// update resources toolbar
document.querySelector('#resources-iron .white-text').innerText = "<%= @resources[:iron] %>"
document.querySelector('#resources-wood .white-text').innerText = "<%= @resources[:wood] %>"
document.querySelector('#resources-water .white-text').innerText = "<%= @resources[:water] %>"
document.querySelector('#resources-gold .white-text').innerText = "<%= @resources[:gold] %>"
document.querySelector('#resources-gems .white-text').innerText = "<%= current_user.gems %>"

// update resources in trade page
document.querySelector('[data-resource="iron"]').dataset.amount = "<%= @resources[:iron] %>"
document.querySelector('[data-resource="wood"]').dataset.amount = "<%= @resources[:wood] %>"
document.querySelector('[data-resource="water"]').dataset.amount = "<%= @resources[:water] %>"
document.querySelector('[data-resource="gold"]').dataset.amountt = "<%= @resources[:gold] %>"


// sweet alert....

// use @data
<% unless @error %>
  <% if @units.count > 1 %>
    <% names = @units.take(2).map { |u| u[:name] }.join(', ') %>
    <% names += " and #{@units.count - 2} other soldiers" %>
    swal({
      title: "Congratulations!",
      text: "<%= names %> have joined your army.",
      icon: "success"
    })
  <% else %>
    swal({
      title: "Congratulations!",
      text: "<%= @units.first[:name] %> has joined your army.",
      icon: "success"
    })

  <% end %>
<% else %>
  swal({
    title: "Not enough gems!",
    text: "<%= @error %>",
    icon: "error"
  })
<% end %>


// initSweetalert('#sweet-alert-demo', {
//   title: "A nice alert",
//   text: "This is a great alert, isn't it?",
//   icon: "success"
// });

app/views/user_units/github_bouns.html.erb
 <div class="tab-pane fade" id="dudes" role="tabpanel">
        <p>Trade in Gems to gain more units!</p>
          <div class="first-row-exchange">
          <div class="one-warrior">
              <a href="#" class="resource-chooser" data-resource="gems" data-amount="10">
                <div class="card-trip-exchange">
                  <img src="https://pbs.twimg.com/profile_images/531994916181012480/EBap51cO_400x400.png" />
                  <div class="card-trip-infos">
                  <h2>1 Fighter</h2>
                  <h2>10 Gems</h2>
                  </div>
                </div>
              </a>
            </div>

         <div class="ten-warriors">
              <a href="#" class="resource-chooser" data-resource="gems" data-amount="90">
                <div class="card-trip-exchange">
                  <img src="https://pbs.twimg.com/profile_images/531994916181012480/EBap51cO_400x400.png">

                  <div class="card-trip-infos">
                  <h2>10 Fighters</h2>
                  <h2>90 Gems</h2>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="second-row-exchange">

            <div class="one-mage">
              <a href="#" class="resource-chooser" data-resource="gems" data-amount="10">
                <div class="card-trip-exchange">
                  <img src="https://pbs.twimg.com/profile_images/531994916181012480/EBap51cO_400x400.png" />
                  <div class="card-trip-infos">
                  <h2>1 Mage</h2>
                  <h2>10 Gems</h2>
                  </div>
                </div>
              </a>
            </div>

            <div class="ten-mages">
              <a href="#" class="resource-chooser" data-resource="gems" data-amount="90">
                <div class="card-trip-exchange">
                  <img src="https://pbs.twimg.com/profile_images/531994916181012480/EBap51cO_400x400.png"/>
                  <div class="card-trip-infos">
                  <h2>10 Mages</h2>
                  <h2>90 Gems</h2>
                  </div>
                </div>
              </a>
            </div>
          </div>

app/views/user_units/old_new.html.erb
<body style="background-color: black">
<div id="addUserUnitCarousel" class="carousel slide" data-ride="carousel">
<h1 style="z-index: 444;position: absolute;top: 42px;right: 8px;text-align: center;">
  <%= current_user.gems %> <img src="https://pbs.twimg.com/profile_images/531994916181012480/EBap51cO_400x400.png" alt="" style="width:40px;height: 40px">
</h1>
  <ol class="carousel-indicators">
    <li data-target="#addUserUnitCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#addUserUnitCarousel" data-slide-to="1"></li>
    <li data-target="#addUserUnitCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">

    <div class="carousel-item active">
      <div class = 'btn-base'>
        <a href="<%= games_main_path %>">
         <%#= image_tag 'base_btn.png' %>
        </a>
      </div>
      <%= cl_image_tag('firstmeeting1_xusbw5', width: 200, height: 400,
                       crop: :fill, class: 'd-block w-100 h-100') %>
      <div class="carousel-caption">
        <h1> Buy a Fighter!</h1>
        <div class="buy-fighter-buttons">
          <div>
            <%= link_to '#',
                        data: { amount: 1 },
                        id: 'add-one-unit' do %>
                      <div class='gem'>
                        10<br>
                        +1<img src="https://pbs.twimg.com/profile_images/531994916181012480/EBap51cO_400x400.png" alt="" style="width:40px;height: 40px">
                      </div>

            <% end %>

          </div>
          <div>
            <%= link_to '#',
                        data: { amount: 10 },
                        id: 'add-ten-units' do %>
                        <div class='gem'>
                          90<br>
                          +10<img src="https://pbs.twimg.com/profile_images/531994916181012480/EBap51cO_400x400.png" alt="" style="width:40px;height: 40px">
                        </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>



    <div class="carousel-item">
      <div class = 'btn-base'>
        <a href="<%= games_main_path %>">
         <%#= image_tag 'base_btn.png' %>
        </a>
      </div>

      <%= cl_image_tag('mages1_cqusxs', width: 200, height: 400,
                       crop: :fill, class: 'd-block w-100 h-100') %>
      <div class="carousel-caption">
        <h1> Buy a Mage!</h1>
        <div class="buy-fighter-buttons">
          <div><%= link_to '#',
                        data: { amount: 1 },
                        id: 'add-one-unit' do %>
                      <div class='gem'>
                        10<br>
                        +1 <img src="https://pbs.twimg.com/profile_images/531994916181012480/EBap51cO_400x400.png" alt="" style="width:40px;height: 40px">
                      </div>

            <% end %>

          </div>
          <div>
            <%= link_to '#',
                        data: { amount: 10 },
                        id: 'add-ten-units' do %>
                        <div class='gem'>
                          90<br>
                          +10 <img src="https://pbs.twimg.com/profile_images/531994916181012480/EBap51cO_400x400.png" alt="" style="width:40px;height: 40px">
                        </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>


    <div class="carousel-item">
      <div class = 'btn-base'>
        <a href="<%= games_main_path %>">
         <%#= image_tag 'base_btn.png' %>
        </a>
      </div>
      <%= cl_image_tag('caravan2_rwroyn', width: 100, height: 200,
                       crop: :fill, class: 'd-block w-100 h-100') %>
      <div class="carousel-caption">
        <h1>Something to Trade?</h1>
        <div class="buy-fighter-buttons">
          <div id="add-one-unit" data-amount='1'>
            <%= link_to 'Wood', '#', class: 'btn btn-wood rounded' %>
          </div>
          <div id="add-five-unit" data-amount='5'>
            <%= link_to 'Water', '#', class: 'btn btn-water rounded' %>
          </div>
          <div id="add-one-unit" data-amount='1'>
            <%= link_to 'Iron', '#', class: 'btn btn-iron rounded' %>
          </div>
          <div id="add-five-unit" data-amount='5'>
            <%= link_to 'Gold', '#', class: 'btn btn-gold rounded' %>
          </div>
        </div>
      </div>
    </div>




  </div>
  <a class="carousel-control-prev" href="#addUserUnitCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#addUserUnitCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<script>

  async function postData(url , data ) {
    // Default options are marked with *
    const response = await fetch(url, {
      method: 'POST', // *GET, POST, PUT, DELETE, etc.
      mode: 'cors', // no-cors, *cors, same-origin
      cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
      credentials: 'same-origin', // include, *same-origin, omit
      headers: {
        'Content-Type': 'application/json'
        // 'Content-Type': 'application/x-www-form-urlencoded',
      },
      redirect: 'follow', // manual, *follow, error
      referrerPolicy: 'no-referrer', // no-referrer, *client
      body: JSON.stringify(data) // body data type must match "Content-Type" header
    });
    return await response.json(); // parses JSON response into native JavaScript objects
  }

  let addOne = document.querySelector('#add-one-unit');
  let addTen = document.querySelector('#add-ten-units');

  addOne.addEventListener('click', (e) => {
    e.preventDefault()
    postData('../user_units', { amount: 1 })
      .then((data) => {
        console.log(data); // JSON data parsed by `response.json()` call
        data.forEach ((data) => {
          alert(`You just got\n
            Name : ${data[0]}\n
            Rarity : ${data[1].toUpperCase()}\n
             his Stats:\n
             Attack: ${data[2]}\n
             Defense: ${data[3]}`);
        });
      });
  })

  addTen.addEventListener('click', (e) => {
    e.preventDefault()
    postData('../user_units', { amount: 10 })
      .then((data) => {
        console.log(data);
        data.forEach ((data) =>{
          alert(`You just got\n
            Name : ${data[0]}\n
            Rarity : ${data[1].toUpperCase()}\n
             his Stats:\n
             Attack: ${data[2]}\n
             Defense: ${data[3]}`);
        });
      })
  });

</script>

app/views/user_units/olddddd_new.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="exchange-tab" data-toggle="tab" href="#exchanged" role="tab"><i class="fas fa-exchange-alt fa-2x"></i></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="dudes-tab" data-toggle="tab" href="#dudes" role="tab"><i class="fas fa-users fa-2x"></i></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="structures-tab" data-toggle="tab" href="#structures" role="tab"><i class="fas fa-tools fa-2x"></i></a>
  </li>
</ul>


<!-- approach 1 -->
 <!-- send get request , 'shop/:filter' -->
 <!-- @search = params[filter'] -->
 <!-- approach 2 -->
 <!-- javascript when filter is clicked -> display:none for non related , display: block for filter choice -->
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="exchanged" role="tabpanel">
    <div class="pg-exchange">
      <p>Trade 20 units of any resource into 1 <img src="https://pbs.twimg.com/profile_images/531994916181012480/EBap51cO_400x400.png" alt="" style="width:25px;height: 25px"></p>
      <%= form_tag inventory_exchange_path do %>
        <div class="resources">
          <div class="first-row-exchange">
            <div class="exchange-wood">
              <a href="#" class="resource-chooser" data-resource="wood" data-amount="100">
                <div class="card-trip-exchange">
                  <img src="https://image.flaticon.com/icons/svg/395/395005.svg" />

                  <div class="card-trip-infos">
                  <h2>Wood</h2>
                  </div>
                </div>
              </a>
            </div>

            <div class="exchange-water">
              <a href="#" class="resource-chooser" data-resource="water" data-amount="100">
                <div class="card-trip-exchange">
                  <img src="https://image.flaticon.com/icons/svg/315/315339.svg" />

                  <div class="card-trip-infos-exchange">
                  <h2>Water</h2>
                  </div>
                </div>
              </a>
            </div>
          </div>
          <div class="second-row-exchange">

            <div class="exchange-metal">
              <a href="#" class="resource-chooser" data-resource="metal" data-amount="100">
                <div class="card-trip-exchange">
                  <img src="https://image.flaticon.com/icons/svg/605/605702.svg" />
                  <div class="card-trip-infos">
                  <h2>Iron</h2>
                  </div>
                </div>
              </a>
            </div>

            <div class="exchange-gold">
              <a href="#" class="resource-chooser" data-resource="gold" data-amount="5">
                <div class="card-trip-exchange">
                  <img src="https://image.flaticon.com/icons/svg/362/362944.svg" />

                  <div class="card-trip-infos">
                  <h2>Gold</h2>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>

        <div class="submitted-exchange-fields">
            <div class="quant-exchanged">
            <%= number_field_tag :amount, 0, min: 0, step: 20 %>
            </div>

            <%= hidden_field_tag 'material', :wood %>
            <%= button_tag(type: "submit", class: "exchange-btn") do %>
                Exchange <i class="fas fa-exchange-alt"></i>
            <% end %>
          <% end %>
        </div>
    </div>
  </div>
  <div class="tab-pane fade" id="dudes" role="tabpanel">
        <h1>this is the dudes page</h1>
  </div>

  <div class="tab-pane fade" id="structures" role="tabpanel">
      <div class="structures">
        <%= form_tag structures_buy_path do %>
        <div class="first-row-structure">
          <div class="structure-barrack">
            <a href="#" class="structure-selector" data-structure="barrack"></a>
            <div class="card-trip-structure">
              <img src="https://image.flaticon.com/icons/svg/395/395005.svg" />


              <div class="card-trip-infos">
              <h2>Barrack</h2>
              </div>
            </div>


          </div>
          <div class="structure-boat">
            <a href="#" class="structure-selector" data-structure="boat"></a>
            <div class="card-trip-structure">
              <img src="https://image.flaticon.com/icons/svg/395/395005.svg" />

              <div class="card-trip-infos">
              <h2>Boat</h2>
              </div>
            </div>

          </div>
        </div>
        <div class="second-row-structure">
          <div class="structure-medic">
            <a href="#" class="structure-selector" data-structure="medic"></a>
            <div class="card-trip-structure">
              <img src="https://image.flaticon.com/icons/svg/395/395005.svg" />

              <div class="card-trip-infos">
              <h2>Medical Center</h2>
              </div>
            </div>


          </div>
          <div class="structure-wheel">
            <a href="#" class="structure-selector" data-structure="wheel"></a>
            <div class="card-trip-structure">
              <img src="https://image.flaticon.com/icons/svg/395/395005.svg" />

              <div class="card-trip-infos">
              <h2>Water Wheel</h2>
              </div>
            </div>

          </div>
        </div>


        <%= hidden_field_tag 'material', :wood %>
        <%= button_tag(type: "submit", class: "exchange-btn") do %>
            Exchange <i class="fas fa-exchange-alt"></i>
        <% end %>
      <% end %>
      </div>
  </div>


</div>
<div class="bar-container" style="background-color: black">
  <div class="bd-highlight res-bar">

     <div class="d-flex">
      <p class='white-text'>5</p>
     <img src="<%= asset_path( 'iron_new.svg' ) %>" height="32px" width="24px" />
     </div>

     <div class ='d-flex'>
     <p class='white-text'>5</p>
     <img src="<%= asset_path( 'wood_new.svg' ) %>" height="32px" width="24px" />
     </div>

      <div class ='d-flex'>
     <p class='white-text'>5</p>
     <img src="<%= asset_path( 'water_new.svg' ) %>" height="32px" width="24px" />
     </div>

      <div class ='d-flex'>
     <p class='white-text'>5</p>
     <img src="<%= asset_path( 'gold_new.svg' ) %>" height="40px" width="32px" />
     </div>

      <div class ='d-flex'>
     <p class='white-text'>5</p>
     <img src="<%= asset_path( 'gem.png' ) %>" height="40px" width="32px" />
     </div>

   </div>
 </div>

<!--
 <div class="tab-pane fade" id="structures" role="tabpanel">
    <div class="structures">
      <%= form_tag structures_buy_path do %>
      <div class="first-row-structure">
        <div class="structure-barrack">
          <a href="#" class="structure-selector" data-structure="barrack"></a>
          <div class="card-trip-structure">
            <img src="https://image.flaticon.com/icons/svg/395/395005.svg" />


            <div class="card-trip-infos">
            <h2>Wood</h2>
            </div>
          </div>


        </div>
        <div class="structure-boat">
          <a href="#" class="structure-selector" data-structure="boat"></a>
          <div class="card-trip-structure">
            <img src="https://image.flaticon.com/icons/svg/395/395005.svg" />

            <div class="card-trip-infos">
            <h2>Wood</h2>
            </div>
          </div>

        </div>
      </div>
      <div class="second-row-structure">
        <div class="structure-medic">
          <a href="#" class="structure-selector" data-structure="medic"></a>
          <div class="card-trip-structure">
            <img src="https://image.flaticon.com/icons/svg/395/395005.svg" />

            <div class="card-trip-infos">
            <h2>Wood</h2>
            </div>
          </div>


        </div>
        <div class="structure-wheel">
          <a href="#" class="structure-selector" data-structure="wheel"></a>
          <div class="card-trip-structure">
            <img src="https://image.flaticon.com/icons/svg/395/395005.svg" />

            <div class="card-trip-infos">
            <h2>Wood</h2>
            </div>
          </div>

        </div>
      </div>


      <%= hidden_field_tag 'material', :wood %>
      <%= button_tag(type: "submit", class: "structure-btn") do %>
          Exchange <i class="fas fa-exchange-alt"></i>
      <% end %>
    <% end %>
    </div>
</div> -->


<!-- <div class = 'btn-base'>
  <a href="<%= games_main_path %>">
  </a>
</div>
 -->


 <div class="resource-price-bar">
    <div class="resource-price">
     <p>20</p>
     <img src="<%= asset_path( 'gold_new.svg' ) %>" height="24px" width="16px" />
   </div>
   <div class="resource-price">
     <p>20</p>
     <img src="<%= asset_path( 'wood_new.svg' ) %>" height="24px" width="16px" />
   </div>
   <div class="resource-price">
     <p>20</p>
     <img src="<%= asset_path( 'iron_new.svg' ) %>" height="24px" width="16px" />
   </div>
   <div class="resource-price">
     <p>20</p>
     <img src="<%= asset_path( 'water_new.svg' ) %>" height="24px" width="16px" />
   </div>
 </div>